#! /bin/bash 
# SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

# Picom 
picom --experimental-backends 

# Random picture with feh
feh --bg-fill ~/Bilder/wallpapers/bg_17.jpg
# Polybar
$HOME/.config/polybar/forest/launch.sh


bspc monitor DP-2 -d 4 5 6 
bspc monitor HDMI-0 -d 1 2 3 
bspc monitor DP-1 -d 7 8 9 

bspc config border_width        2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^II'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

