#! /bin/bash
# SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

# Picom 
picom --experimental-backends 

bspc monitor DP-2 -d IV V VI 
bspc monitor HDMI-0 -d I II III 
bspc monitor DP-1 -d VII VIII IX

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^II'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Polybar
$HOME/.config/polybar/forest/launch.sh
